### ISSUE TITLE
Network.cpp is missing and sys/resources.h is missing 

### ISSUE THREAD

**Issue by Maqsood2300** [Mcdouglas-X/KANGAROO-256-CUSTOM#1]
Bro when compiling in vs19 it doesn't compile error coming no network file and sys/resources.h is missing

**Comment by Maqsood2300** [comment]
Bro mcdouglas-x why I cannot build this solution always giving error 
![Uploading 17295253714695375054862000223476.jpg…]()

**Comment by Maqsood2300** [comment]
![Uploading IMG_20241021_204927_699.jpg…]()
Now sys/resource.h no such file or directory error is comi
![Uploading 17295256697775323564517424326747.jpg…]()
ng

**Comment by Mcdouglas-X** [comment]
This kangaroo is for offline use, network.cpp is not required, please download again and compile using WLS.
example: 
1- wsl --install
2- Reboot system
3- sudo apt update
4- sudo apt install build-essential
5- make clean
6- make cpu=1

run
./kangaroo-256 55.txt

**Comment by Maqsood2300** [comment]
I am compiling on windows

**Comment by Mcdouglas-X** [comment]
"WLS" it allows you to run a Linux environment directly on your Windows computer, essentially giving you a Linux console within Windows.

**Comment by ghost** [comment]
Hi mcdouglas if compiling for gpu is it the same process? Thanks

**Comment by Maqsood2300** [comment]
Bro it still not compiling

**Comment by Mcdouglas-X** [comment]
> Hi mcdouglas if compiling for gpu is it the same process? Thanks

yes, make gpu=1

> Bro it still not compiling

try:
sudo apt update
sudo apt install g++
sudo apt install make

You must be having problems with the libraries. I just downloaded it and it compiles without issues. Be more specific about the error you’re getting in the console.

**Comment by Maqsood2300** [comment]
Usr/local/cuda/bin/nvcc no such file or directory 
Make: *** [makefile:92: obj/GPU/GPUEngine.o] error 127

**Comment by Mcdouglas-X** [comment]
> Usr/local/cuda/bin/nvcc no such file or directory Make: *** [makefile:92: obj/GPU/GPUEngine.o] error 127

https://github.com/Mcdouglas-X/KANGAROO-256-CUSTOM#linux

**Comment by ghost** [comment]
Im having the same issue can share the executable for both cpu/gpu. Thanks

**Comment by Maqsood2300** [comment]
Bro can we compile this on window only minor error is coming sys/resources.h is not directory or file not found

**Comment by Maqsood2300** [comment]
Mcdouglas-x bro can you share compiled version of window and wsl

**Comment by Mcdouglas-X** [comment]
> Bro can we compile this on window only minor error is coming sys/resources.h is not directory or file not found

You must install your version of "Cuda Toolkit" on WLS.

"sys/Resources.h" is not for Windows, if you want to compile in Windows you need to modify the kangaroo.h and other parts of the code to include an adapted version for Windows.

**Comment by Maqsood2300** [comment]
Bro i install cuda toolkit 12.6 and g++ 11 and compile code and it's done when I star program with it does start  but
error comes GPU code not compiled  use -dwithgpu  when compiling
No CPU or GPU thread exiting

**Comment by Maqsood2300** [comment]
For CPU it's working but for GPU not working when I was compiling 
Make GPU=1 ccap=80 all

**Comment by agoora** [comment]
I confirm that compilation in linux for GPU is not functional!
Please check the code and fix it!

**Comment by Mcdouglas-X** [comment]
**update**:

please download again and compile using WLS(Windows).
example:
1- wsl --install
2- Reboot system
3- sudo apt update
4- sudo apt install build-essential
5- install cuda toolkit for WLS
6- make clean
7- make cpu=1
7.1- make gpu=1

run
./kangaroo-256 55.txt
./kangaroo-256 -gpu 55.txt
