### ISSUE TITLE
cant compile

### ISSUE THREAD

**Issue by thunderbolt78** [Mcdouglas-X/KANGAROO-256-CUSTOM#2]
i use windows 10 and visual code 2019, cuda 10.2 but i cant compile , any suggestions ? are you able to provide the compiled version here ?

1>GPUEngine.cu
1>Backup.cpp
1>C:\tmp\KANGAROO-256-CUSTOM-main\Kangaroo.h(32,10): fatal error C1083: Cannot open include file: 'sys/resource.h': No such file or directory
1>Check.cpp
1>C:\tmp\KANGAROO-256-CUSTOM-main\Kangaroo.h(32,10): fatal error C1083: Cannot open include file: 'sys/resource.h': No such file or directory
1>HashTable.cpp
1>Merge.cpp
1>C:\tmp\KANGAROO-256-CUSTOM-main\Kangaroo.h(32,10): fatal error C1083: Cannot open include file: 'sys/resource.h': No such file or directory
1>PartMerge.cpp
1>C:\tmp\KANGAROO-256-CUSTOM-main\Kangaroo.h(32,10): fatal error C1083: Cannot open include file: 'sys/resource.h': No such file or directory
1>Int.cpp
1>IntGroup.cpp
1>IntMod.cpp
1>main.cpp
1>C:\tmp\KANGAROO-256-CUSTOM-main\Kangaroo.h(32,10): fatal error C1083: Cannot open include file: 'sys/resource.h': No such file or directory
1>Point.cpp
1>Random.cpp
1>SECP256K1.cpp
1>Thread.cpp
1>C:\tmp\KANGAROO-256-CUSTOM-main\Kangaroo.h(32,10): fatal error C1083: Cannot open include file: 'sys/resource.h': No such file or directory
1>Timer.cpp
1>Kangaroo.cpp
1>C:\tmp\KANGAROO-256-CUSTOM-main\Kangaroo.h(32,10): fatal error C1083: Cannot open include file: 'sys/resource.h': No such file or directory
1>Done building project "Kangaroo.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Mcdouglas-X** [comment]
@thunderbolt78 
use  WLS:
[steps](https://github.com/Mcdouglas-X/KANGAROO-256-CUSTOM/issues/1#issuecomment-2433172965)
